name: one_cask
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  general_repository:
    path: packages/general_repository
  authentication_repository:
    path: packages/authentication_repository
  cache:
    path: packages/cache
  localization:
    path: packages/localization
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  formz: ^0.8.0
  flutter_svg: ^2.1.0
  connectivity_plus: ^6.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/my_collection_mock.json


  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 300
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/Lato-Italic.ttf
          weight: 400
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
    - family: EBGaramond
      fonts:
        - asset: assets/fonts/EBGaramond-Regular.ttf
          weight: 400
        - asset: assets/fonts/EBGaramond-Bold.ttf
          weight: 700
        - asset: assets/fonts/EBGaramond-Italic.ttf
          weight: 400
        - asset: assets/fonts/EBGaramond-Medium.ttf
          weight: 500
        - asset: assets/fonts/EBGaramond-SemiBoldItalic.ttf
          weight: 600



